version: '3.3'

services:
    gitlab:
      image: 'gitlab/gitlab-ee'
      container_name: "gitlab"
      restart: always
      hostname: 'gitlab'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://127.0.0.1:8080'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          gitlab_rails['gitlab_shell_ssh_port'] = 22
      ports:
        - '8080:8080'
        - '443:443'
        - '22:22'
      volumes:
        - ./config:/etc/gitlab
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab